### ISSUE TITLE
More descriptive name?

### ISSUE THREAD

**Issue by jodaiber** [dbpedia-spotlight/DBpediaSpotlight.js#1]
Hey,
I find the name MDBSpotlight a bit confusing, maybe this repo could be renamed to something more descriptive like Spotlight.js?

Jo

**Comment by ali1k** [comment]
Hi Jo,
I will think about a more descriptive name (I am not satisfied with the current name either!). Unfortunately Spotlight.js does not reflect the multilinguality feature and is already taken at npm https://www.npmjs.org/package/SpotlightJS
If you have more suggestions just let me know....

**Comment by pablomendes** [comment]
I like the .js idea. And I don't think that multilingual needs to be in the
name. Isn't the current spotlight demo in http://spotlight.dbpedia.org/demo/
multilingual anyway?

What about:
DBpediaSpotlight.js (my favorite)
MultilingSpotlight.js
MultilingualSpotlight.js
I18nSpotlight.js

**Comment by jodaiber** [comment]
+1 for DBpediaSpotlight.js

Maybe @m1ci would be interested in merging these two repositories, so that there could be only one Spotlight.js, after all?

**Comment by m1ci** [comment]
Hi Joachim, all,
Sure, why not! Let me know how can I help...
If I can vote, I would vote for Spotlight.js or DBpediaSpotlight.js
BTW, I believe for many people Spotlight is synonym for DBpedia Spotlight ;)

**Comment by ali1k** [comment]
I like DBpediaSpotlight.js more but I am fine with Spotlight.js as well. The only problem is that there is already Spotlight npm package: https://www.npmjs.org/package/spotlight package with different purpose.
For people outside the SW community, spotlight doesn't always mean DBpedia Spotlight as I assume!
we can then change the repo name to DBpediaSpotlight.js and publish the npm package as dbpedia-spotlight

We would need to create a bower package too.
@m1ci : that would be great if you contribute here as well and forward the users of your package to this one.

**Comment by jodaiber** [comment]
So, my suggestion would be:
- adapt the two packages so that the API is more or less the same
- rename this repo to Spotlight.js or DBpediaSpotlight.js
- change https://www.npmjs.org/package/SpotlightJS to this repo and add both of you as authors there

What do you think?

**Comment by m1ci** [comment]
@jodaiber I am fine with your proposal.

**Comment by ali1k** [comment]
I changed the name and created a new npm package at https://www.npmjs.org/package/dbpedia-spotlight
@jodaiber let's start collaboration and redirect your Spotlight.js package to DBpediaSpotlight.js
