### ISSUE TITLE
The service is not working

### ISSUE THREAD

**Issue by bayomim** [dbpedia-spotlight/DBpediaSpotlight.js#5]
Hi, 
I used this module before and it worked fine for me, but now it seams that the service itself (spotlight.sztaki.hu) is not working and also the demo (http://dbpedia-spotlight.github.io/demo/) 

Do you have any idea what is going on? and do you have any alternative?

Thanks.

**Comment by jodaiber** [comment]
Hey @bayomim,

I restarted the endpoint. Keep in mind that this endpoint is basically just a demo and is heavily used. If you want real reliability and speed, you can download a model and run it on your own machine.

Best,
Jo

**Comment by bayomim** [comment]
That's great, thanks
